import * as monaco from 'monaco-editor';
import { options } from './common';

export const envCommands = [
  '\\begin',
  '\\end',
  '\\envdef',
  '\\newenvironment',
  '\\newtheorem',
  '\\renewenvironment',
];

export const envStarCommands = ['\\newenvironment*', '\\renewenvironment*', '\\newtheorem*'];

export const mathEnvironments = [
  'align',
  'align*',
  'alignat',
  'alignat*',
  'equation',
  'equation*',
  'gather',
  'gather*',
  'multline',
  'multline*',
];

export interface CompletionItem {
  mode: 'M' | 'T' | 'MT';
  kind?: monaco.languages.CompletionItemKind;
  insertText?: string;
  insertTextRules?: monaco.languages.CompletionItemInsertTextRule;
  signature?: string;
  deprecated?: boolean;
}

export const commandDictionary: { [key: string]: CompletionItem } = {
  '\\AA': { mode: 'T' },
  '\\addtocounter': { mode: 'MT', signature: '\\addtocounter{计数器}{值}' },
  '\\adef': { mode: 'MT', signature: '\\adef<命令><参数>{定义}' },
  '\\AE': { mode: 'T' },
  '\\ae': { mode: 'T' },
  '\\alet': { mode: 'MT', signature: '\\alet<命令><命令>' },
  '\\Alph': { mode: 'MT', signature: '\\Alph{计数器}' },
  '\\alph': { mode: 'MT', signature: '\\alph{计数器}' },
  '\\arabic': { mode: 'MT', signature: '\\arabic{计数器}' },
  '\\backslash': { mode: 'MT' },
  '\\begin': { mode: 'MT', insertText: '\\begin{', signature: '\\begin{环境}' },
  '\\begingroup': { mode: 'MT' },
  '\\bf': { mode: 'T' },
  '\\bibitem': { mode: 'T', signature: '\\bibitem[编号]{标签}' },
  '\\bullet': { mode: 'MT' },
  '\\c': { mode: 'T', signature: '\\c{}' },
  '\\cite': { mode: 'T', signature: '\\cite[内容]{标签}' },
  '\\code': { mode: 'T', signature: '\\code{代码}' },
  '\\codeblock': { mode: 'T', signature: '\\codeblock{代码}' },
  '\\color': { mode: 'T', signature: '\\color{颜色代码}' },
  '\\colour': { mode: 'T', signature: '\\colour{颜色代码}' },
  '\\corollaryname': { mode: 'MT' },
  '\\dagger': { mode: 'MT' },
  '\\ddagger': { mode: 'MT' },
  '\\def': { mode: 'MT', signature: '\\def<命令><参数>{定义}' },
  '\\definitionname': { mode: 'MT' },
  '\\edef': { mode: 'MT', signature: '\\edef<命令><参数>{定义}' },
  '\\em': { mode: 'T' },
  '\\emph': { mode: 'T', signature: '\\emph{文字}' },
  '\\end': { mode: 'MT', signature: '\\end{环境}' },
  '\\endgroup': { mode: 'MT' },
  '\\english': { mode: 'MT', signature: '\\english[]' },
  '\\envadef': { mode: 'MT', signature: '\\envadef{环境}{参数}{开始}{结束}' },
  '\\envdef': { mode: 'MT', signature: '\\envdef{环境}{参数}{开始}{结束}' },
  '\\envpdef': { mode: 'MT', signature: '\\envpdef{环境}{参数}{开始}{结束}' },
  '\\eqno': { mode: 'M' },
  '\\eqref': { mode: 'T', signature: '\\eqref{}' },
  '\\floatright': { mode: 'T', signature: '\\floatright{内容}' },
  '\\gdef': { mode: 'MT', signature: '\\gdef<命令><参数>{定义}' },
  '\\glet': { mode: 'MT', signature: '\\glet<命令><命令>' },
  '\\H': { mode: 'T', signature: '\\H{}' },
  '\\href': { mode: 'T', signature: '\\href{链接}{文字}' },
  '\\i': { mode: 'MT' },
  '\\it': { mode: 'T' },
  '\\item': { mode: 'T', signature: '\\item[编号]' },
  '\\j': { mode: 'MT' },
  '\\l': { mode: 'T' },
  '\\L': { mode: 'T' },
  '\\label': { mode: 'T', signature: '\\label{标签}' },
  '\\lang': { mode: 'T', signature: '\\lang{语言代码}{文字}' },
  '\\lemmaname': { mode: 'T' },
  '\\leqno': { mode: 'M' },
  '\\let': { mode: 'MT', signature: '\\let<命令><命令>' },
  '\\md': { mode: 'T' },
  '\\newcommand': { mode: 'MT', signature: '\\newcommand<命令>[参数]{定义}' },
  '\\newcounter': { mode: 'MT', signature: '\\newcounter[计数器]' },
  '\\newenvironment': { mode: 'MT', signature: '\\newenvironment{环境}[参数]{开始}{结束}' },
  '\\newtheorem': { mode: 'MT', signature: '\\newtheorem{环境}{名称}' },
  '\\nosectionnumbers': { mode: 'T' },
  '\\numbersections': { mode: 'T' },
  '\\numbersubsections': { mode: 'T' },
  '\\numbersubsubsections': { mode: 'T' },
  '\\numberwithin': { mode: 'MT', signature: '\\numberwithin{子计数器}{父计数器}' },
  '\\o': { mode: 'T' },
  '\\O': { mode: 'T' },
  '\\oe': { mode: 'T' },
  '\\OE': { mode: 'T' },
  '\\operatornamewithlimits': { mode: 'M', signature: '\\operatornamewithlimits{文字}' },
  '\\par': { mode: 'T' },
  '\\pdef': { mode: 'MT', signature: '\\pdef<命令><参数>{定义}' },
  '\\plet': { mode: 'MT', signature: '\\plet<命令><命令>' },
  '\\proofname': { mode: 'T' },
  '\\propositionname': { mode: 'T' },
  '\\qed': { mode: 'T' },
  '\\qedhere': { mode: 'MT' },
  '\\qedsymbol': { mode: 'T' },
  '\\qquad': { mode: 'T' },
  '\\quad': { mode: 'T' },
  '\\r': { mode: 'T', signature: '\\r{}' },
  '\\ref': { mode: 'MT', signature: '\\ref{标签}' },
  '\\refname': { mode: 'T' },
  '\\refstepcounter': { mode: 'MT', signature: '\\refstepcounter{计数器}' },
  '\\remarkname': { mode: 'T' },
  '\\renewcommand': { mode: 'MT', signature: '\\renewcommand<命令>[参数]{定义}' },
  '\\renewenvironment': { mode: 'MT', signature: '\\renewenvironment{环境}[参数]{开始}{结束}' },
  '\\reqno': { mode: 'M' },
  '\\rm': { mode: 'T' },
  '\\Roman': { mode: 'MT', signature: '\\Roman{计数器}' },
  '\\roman': { mode: 'MT', signature: '\\roman{计数器}' },
  '\\S': { mode: 'T' },
  '\\section': { mode: 'T', signature: '\\section{标题}' },
  '\\setcounter': { mode: 'MT', signature: '\\setcounter{计数器}' },
  '\\setdisplaytitle': { mode: 'T', signature: '\\setdisplaytitle{文字}' },
  '\\sethtmltitle': { mode: 'T', signature: '\\sethtmltitle{文字}' },
  '\\setlanguage': { mode: 'T', signature: '\\setlanguage{语言代码}' },
  '\\size': { mode: 'T', signature: '\\size{大小}' },
  '\\ss': { mode: 'T' },
  '\\SS': { mode: 'T' },
  '\\stepcounter': { mode: 'T', signature: '\\stepcounter{计数器}' },
  '\\subpage': { mode: 'T', signature: '\\subpage[编号]{页标题}[文字]' },
  '\\subsection': { mode: 'T', signature: '\\subsection{标题}' },
  '\\subsubpage': { mode: 'T', signature: '\\subsubpage[编号]{页标题}[文字]' },
  '\\subsubsection': { mode: 'T', signature: '\\subsubsection{标题}' },
  '\\subsubsubpage': { mode: 'T', signature: '\\subsubsubpage[编号]{页标题}[文字]' },
  '\\tdef': { mode: 'MT', signature: '\\tdef<命令><参数>{定义}' },
  '\\textbf': { mode: 'MT', signature: '\\textbf{文字}' },
  '\\textcolor': { mode: 'T', signature: '\\textcolor{颜色}{文字}' },
  '\\textcolour': { mode: 'T', signature: '\\textcolour{颜色}{文字}' },
  '\\textit': { mode: 'MT', signature: '\\textit{文字}' },
  '\\textmd': { mode: 'MT', signature: '\\textmd{文字}' },
  '\\textrm': { mode: 'MT', signature: '\\textrm{文字}' },
  '\\textsize': { mode: 'T', signature: '\\textsize{大小}{文字}' },
  '\\thmprefix': { mode: 'T' },
  '\\tikz': { mode: 'T', signature: '\\tikz{代码}' },
  '\\tlet': { mode: 'MT', signature: '\\tlet<命令><命令>' },
  '\\tocname': { mode: 'T' },
  '\\u': { mode: 'T', signature: '\\u{}' },
  '\\url': { mode: 'T', signature: '\\url{链接}' },
  '\\v': { mode: 'T', signature: '\\v{}' },
  '\\xeqno': { mode: 'M' },
  '\\above': { mode: 'M' },
  '\\acute': { mode: 'M' },
  '\\alef': { mode: 'M' },
  '\\alefsym': { mode: 'M' },
  '\\aleph': { mode: 'M' },
  '\\allowbreak': { mode: 'M' },
  '\\Alpha': { mode: 'M' },
  '\\alpha': { mode: 'M' },
  '\\amalg': { mode: 'M' },
  '\\And': { mode: 'M' },
  '\\angle': { mode: 'M' },
  '\\approx': { mode: 'M' },
  '\\approxeq': { mode: 'M' },
  '\\arccos': { mode: 'M' },
  '\\arcctg': { mode: 'M' },
  '\\arcsin': { mode: 'M' },
  '\\arctan': { mode: 'M' },
  '\\arctg': { mode: 'M' },
  '\\arg': { mode: 'M' },
  '\\argmax': { mode: 'M' },
  '\\argmin': { mode: 'M' },
  '\\ast': { mode: 'M' },
  '\\asymp': { mode: 'M' },
  '\\atop': { mode: 'M' },
  '\\backepsilon': { mode: 'M' },
  '\\backprime': { mode: 'M' },
  '\\backsim': { mode: 'M' },
  '\\backsimeq': { mode: 'M' },
  '\\bar': { mode: 'M' },
  '\\barwedge': { mode: 'M' },
  '\\Bbb': { mode: 'M' },
  '\\Bbbk': { mode: 'M' },
  '\\bcancel': { mode: 'M' },
  '\\because': { mode: 'M' },
  '\\Beta': { mode: 'M' },
  '\\beta': { mode: 'M' },
  '\\beth': { mode: 'M' },
  '\\between': { mode: 'M' },
  '\\big': { mode: 'M' },
  '\\Big': { mode: 'M' },
  '\\bigcap': { mode: 'M' },
  '\\bigcirc': { mode: 'M' },
  '\\bigcup': { mode: 'M' },
  '\\bigg': { mode: 'M' },
  '\\Bigg': { mode: 'M' },
  '\\biggl': { mode: 'M' },
  '\\Biggl': { mode: 'M' },
  '\\biggm': { mode: 'M' },
  '\\Biggm': { mode: 'M' },
  '\\biggr': { mode: 'M' },
  '\\Biggr': { mode: 'M' },
  '\\bigl': { mode: 'M' },
  '\\Bigl': { mode: 'M' },
  '\\bigm': { mode: 'M' },
  '\\Bigm': { mode: 'M' },
  '\\bigodot': { mode: 'M' },
  '\\bigoplus': { mode: 'M' },
  '\\bigotimes': { mode: 'M' },
  '\\bigr': { mode: 'M' },
  '\\Bigr': { mode: 'M' },
  '\\bigsqcup': { mode: 'M' },
  '\\bigstar': { mode: 'M' },
  '\\bigtriangledown': { mode: 'M' },
  '\\bigtriangleup': { mode: 'M' },
  '\\biguplus': { mode: 'M' },
  '\\bigvee': { mode: 'M' },
  '\\bigwedge': { mode: 'M' },
  '\\binom': { mode: 'M' },
  '\\blacklozenge': { mode: 'M' },
  '\\blacksquare': { mode: 'M' },
  '\\blacktriangle': { mode: 'M' },
  '\\blacktriangledown': { mode: 'M' },
  '\\blacktriangleleft': { mode: 'M' },
  '\\blacktriangleright': { mode: 'M' },
  '\\bm': { mode: 'M' },
  '\\bmod': { mode: 'M' },
  '\\bold': { mode: 'M' },
  '\\boldsymbol': { mode: 'M' },
  '\\bot': { mode: 'M' },
  '\\bowtie': { mode: 'M' },
  '\\Box': { mode: 'M' },
  '\\boxdot': { mode: 'M' },
  '\\boxed': { mode: 'M' },
  '\\boxminus': { mode: 'M' },
  '\\boxplus': { mode: 'M' },
  '\\boxtimes': { mode: 'M' },
  '\\Bra': { mode: 'M' },
  '\\bra': { mode: 'M' },
  '\\braket': { mode: 'M' },
  '\\brace': { mode: 'M' },
  '\\brack': { mode: 'M' },
  '\\breve': { mode: 'M' },
  '\\bull': { mode: 'M' },
  '\\Bumpeq': { mode: 'M' },
  '\\bumpeq': { mode: 'M' },
  '\\cal': { mode: 'M' },
  '\\cancel': { mode: 'M' },
  '\\Cap': { mode: 'M' },
  '\\cap': { mode: 'M' },
  '\\cdot': { mode: 'M' },
  '\\cdotp': { mode: 'M' },
  '\\cdots': { mode: 'M' },
  '\\centerdot': { mode: 'M' },
  '\\cfrac': { mode: 'M' },
  '\\check': { mode: 'M' },
  '\\ch': { mode: 'M' },
  '\\checkmark': { mode: 'M' },
  '\\Chi': { mode: 'M' },
  '\\chi': { mode: 'M' },
  '\\choose': { mode: 'M' },
  '\\circ': { mode: 'M' },
  '\\circeq': { mode: 'M' },
  '\\circlearrowleft': { mode: 'M' },
  '\\circlearrowright': { mode: 'M' },
  '\\circledast': { mode: 'M' },
  '\\circledcirc': { mode: 'M' },
  '\\circleddash': { mode: 'M' },
  '\\circledR': { mode: 'M' },
  '\\circledS': { mode: 'M' },
  '\\clubs': { mode: 'M' },
  '\\clubsuit': { mode: 'M' },
  '\\cnums': { mode: 'M' },
  '\\colon': { mode: 'M' },
  '\\Colonapprox': { mode: 'M' },
  '\\colonapprox': { mode: 'M' },
  '\\Coloneq': { mode: 'M' },
  '\\coloneq': { mode: 'M' },
  '\\Coloneqq': { mode: 'M' },
  '\\coloneqq': { mode: 'M' },
  '\\Colonsim': { mode: 'M' },
  '\\colonsim': { mode: 'M' },
  '\\colorbox': { mode: 'M' },
  '\\complement': { mode: 'M' },
  '\\Complex': { mode: 'M' },
  '\\cong': { mode: 'M' },
  '\\coprod': { mode: 'M' },
  '\\copyright': { mode: 'M' },
  '\\cos': { mode: 'M' },
  '\\cosec': { mode: 'M' },
  '\\cosh': { mode: 'M' },
  '\\cot': { mode: 'M' },
  '\\cotg': { mode: 'M' },
  '\\coth': { mode: 'M' },
  '\\cr': { mode: 'M' },
  '\\csc': { mode: 'M' },
  '\\ctg': { mode: 'M' },
  '\\cth': { mode: 'M' },
  '\\Cup': { mode: 'M' },
  '\\cup': { mode: 'M' },
  '\\curlyeqprec': { mode: 'M' },
  '\\curlyeqsucc': { mode: 'M' },
  '\\curlyvee': { mode: 'M' },
  '\\curlywedge': { mode: 'M' },
  '\\curvearrowleft': { mode: 'M' },
  '\\curvearrowright': { mode: 'M' },
  '\\dag': { mode: 'M' },
  '\\Dagger': { mode: 'M' },
  '\\daleth': { mode: 'M' },
  '\\Darr': { mode: 'M' },
  '\\dArr': { mode: 'M' },
  '\\darr': { mode: 'M' },
  '\\dashleftarrow': { mode: 'M' },
  '\\dashrightarrow': { mode: 'M' },
  '\\dashv': { mode: 'M' },
  '\\dbinom': { mode: 'M' },
  '\\dblcolon': { mode: 'M' },
  '\\ddag': { mode: 'M' },
  '\\ddot': { mode: 'M' },
  '\\ddots': { mode: 'M' },
  '\\deg': { mode: 'M' },
  '\\degree': { mode: 'M' },
  '\\delta': { mode: 'M' },
  '\\Delta': { mode: 'M' },
  '\\det': { mode: 'M' },
  '\\digamma': { mode: 'M' },
  '\\dfrac': { mode: 'M' },
  '\\diagdown': { mode: 'M' },
  '\\diagup': { mode: 'M' },
  '\\Diamond': { mode: 'M' },
  '\\diamond': { mode: 'M' },
  '\\diamonds': { mode: 'M' },
  '\\diamondsuit': { mode: 'M' },
  '\\dim': { mode: 'M' },
  '\\displaystyle': { mode: 'M' },
  '\\div': { mode: 'M' },
  '\\divideontimes': { mode: 'M' },
  '\\dot': { mode: 'M' },
  '\\Doteq': { mode: 'M' },
  '\\doteq': { mode: 'M' },
  '\\doteqdot': { mode: 'M' },
  '\\dotplus': { mode: 'M' },
  '\\dots': { mode: 'M' },
  '\\dotsb': { mode: 'M' },
  '\\dotsc': { mode: 'M' },
  '\\dotsi': { mode: 'M' },
  '\\dotsm': { mode: 'M' },
  '\\dotso': { mode: 'M' },
  '\\doublebarwedge': { mode: 'M' },
  '\\doublecap': { mode: 'M' },
  '\\doublecup': { mode: 'M' },
  '\\Downarrow': { mode: 'M' },
  '\\downarrow': { mode: 'M' },
  '\\downdownarrows': { mode: 'M' },
  '\\downharpoonleft': { mode: 'M' },
  '\\downharpoonright': { mode: 'M' },
  '\\ell': { mode: 'M' },
  '\\empty': { mode: 'M' },
  '\\emptyset': { mode: 'M' },
  '\\enspace': { mode: 'M' },
  '\\Epsilon': { mode: 'M' },
  '\\epsilon': { mode: 'M' },
  '\\eqcirc': { mode: 'M' },
  '\\Eqcolon': { mode: 'M' },
  '\\eqcolon': { mode: 'M' },
  '\\Eqqcolon': { mode: 'M' },
  '\\eqqcolon': { mode: 'M' },
  '\\eqsim': { mode: 'M' },
  '\\eqslantgtr': { mode: 'M' },
  '\\eqslantless': { mode: 'M' },
  '\\equiv': { mode: 'M' },
  '\\Eta': { mode: 'M' },
  '\\eta': { mode: 'M' },
  '\\eth': { mode: 'M' },
  '\\exist': { mode: 'M' },
  '\\exists': { mode: 'M' },
  '\\exp': { mode: 'M' },
  '\\expandafter': { mode: 'M' },
  '\\fallingdotseq': { mode: 'M' },
  '\\fbox': { mode: 'M' },
  '\\fcolorbox': { mode: 'M' },
  '\\Finv': { mode: 'M' },
  '\\flat': { mode: 'M' },
  '\\footnotesize': { mode: 'M' },
  '\\forall': { mode: 'M' },
  '\\frac': { mode: 'M' },
  '\\frak': { mode: 'M' },
  '\\frown': { mode: 'M' },
  '\\futurelet': { mode: 'M' },
  '\\Game': { mode: 'M' },
  '\\Gamma': { mode: 'M' },
  '\\gamma': { mode: 'M' },
  '\\gcd': { mode: 'M' },
  '\\ge': { mode: 'M' },
  '\\genfrac': { mode: 'M' },
  '\\geq': { mode: 'M' },
  '\\geqq': { mode: 'M' },
  '\\geqslant': { mode: 'M' },
  '\\gets': { mode: 'M' },
  '\\gg': { mode: 'M' },
  '\\ggg': { mode: 'M' },
  '\\gggtr': { mode: 'M' },
  '\\gimel': { mode: 'M' },
  '\\global': { mode: 'M' },
  '\\gnapprox': { mode: 'M' },
  '\\gneq': { mode: 'M' },
  '\\gneqq': { mode: 'M' },
  '\\gnsim': { mode: 'M' },
  '\\grave': { mode: 'M' },
  '\\gt': { mode: 'M' },
  '\\gtrdot': { mode: 'M' },
  '\\gtrapprox': { mode: 'M' },
  '\\gtreqless': { mode: 'M' },
  '\\gtreqqless': { mode: 'M' },
  '\\gtrless': { mode: 'M' },
  '\\gtrsim': { mode: 'M' },
  '\\gvertneqq': { mode: 'M' },
  '\\Harr': { mode: 'M' },
  '\\hArr': { mode: 'M' },
  '\\harr': { mode: 'M' },
  '\\hat': { mode: 'M' },
  '\\hbar': { mode: 'M' },
  '\\hdashline': { mode: 'M' },
  '\\hearts': { mode: 'M' },
  '\\heartsuit': { mode: 'M' },
  '\\hline': { mode: 'M' },
  '\\hom': { mode: 'M' },
  '\\hookleftarrow': { mode: 'M' },
  '\\hookrightarrow': { mode: 'M' },
  '\\hphantom': { mode: 'M' },
  '\\hskip': { mode: 'M' },
  '\\hslash': { mode: 'M' },
  '\\hspace': { mode: 'M' },
  '\\htmlClass': { mode: 'M' },
  '\\htmlData': { mode: 'M' },
  '\\htmlId': { mode: 'M' },
  '\\htmlStyle': { mode: 'M' },
  '\\huge': { mode: 'M' },
  '\\Huge': { mode: 'M' },
  '\\iff': { mode: 'M' },
  '\\iiint': { mode: 'M' },
  '\\iint': { mode: 'M' },
  '\\Im': { mode: 'M' },
  '\\image': { mode: 'M' },
  '\\imath': { mode: 'M' },
  '\\impliedby': { mode: 'M' },
  '\\implies': { mode: 'M' },
  '\\in': { mode: 'M' },
  '\\inf': { mode: 'M' },
  '\\infin': { mode: 'M' },
  '\\infty': { mode: 'M' },
  '\\int': { mode: 'M' },
  '\\intercal': { mode: 'M' },
  '\\intop': { mode: 'M' },
  '\\Iota': { mode: 'M' },
  '\\iota': { mode: 'M' },
  '\\isin': { mode: 'M' },
  '\\jmath': { mode: 'M' },
  '\\Join': { mode: 'M' },
  '\\Kappa': { mode: 'M' },
  '\\kappa': { mode: 'M' },
  '\\KaTeX': { mode: 'M' },
  '\\ker': { mode: 'M' },
  '\\kern': { mode: 'M' },
  '\\Ket': { mode: 'M' },
  '\\ket': { mode: 'M' },
  '\\Lambda': { mode: 'M' },
  '\\lambda': { mode: 'M' },
  '\\land': { mode: 'M' },
  '\\langle': { mode: 'M' },
  '\\Larr': { mode: 'M' },
  '\\lArr': { mode: 'M' },
  '\\larr': { mode: 'M' },
  '\\large': { mode: 'M' },
  '\\Large': { mode: 'M' },
  '\\LARGE': { mode: 'M' },
  '\\LaTeX': { mode: 'M' },
  '\\lBrace': { mode: 'M' },
  '\\lbrace': { mode: 'M' },
  '\\lbrack': { mode: 'M' },
  '\\lceil': { mode: 'M' },
  '\\ldotp': { mode: 'M' },
  '\\ldots': { mode: 'M' },
  '\\le': { mode: 'M' },
  '\\leadsto': { mode: 'M' },
  '\\left': { mode: 'M' },
  '\\leftarrow': { mode: 'M' },
  '\\Leftarrow': { mode: 'M' },
  '\\leftharpoondown': { mode: 'M' },
  '\\leftharpoonup': { mode: 'M' },
  '\\leftleftarrows': { mode: 'M' },
  '\\Leftrightarrow': { mode: 'M' },
  '\\leftrightarrow': { mode: 'M' },
  '\\leftrightarrows': { mode: 'M' },
  '\\leftrightharpoons': { mode: 'M' },
  '\\leftrightsquigarrow': { mode: 'M' },
  '\\leftthreetimes': { mode: 'M' },
  '\\leq': { mode: 'M' },
  '\\leqq': { mode: 'M' },
  '\\leqslant': { mode: 'M' },
  '\\lessapprox': { mode: 'M' },
  '\\lessdot': { mode: 'M' },
  '\\lesseqgtr': { mode: 'M' },
  '\\lesseqqgtr': { mode: 'M' },
  '\\lessgtr': { mode: 'M' },
  '\\lesssim': { mode: 'M' },
  '\\lfloor': { mode: 'M' },
  '\\lg': { mode: 'M' },
  '\\lgroup': { mode: 'M' },
  '\\lhd': { mode: 'M' },
  '\\lim': { mode: 'M' },
  '\\liminf': { mode: 'M' },
  '\\limits': { mode: 'M' },
  '\\limsup': { mode: 'M' },
  '\\ll': { mode: 'M' },
  '\\llap': { mode: 'M' },
  '\\llbracket': { mode: 'M' },
  '\\llcorner': { mode: 'M' },
  '\\Lleftarrow': { mode: 'M' },
  '\\lll': { mode: 'M' },
  '\\llless': { mode: 'M' },
  '\\lmoustache': { mode: 'M' },
  '\\ln': { mode: 'M' },
  '\\lnapprox': { mode: 'M' },
  '\\lneq': { mode: 'M' },
  '\\lneqq': { mode: 'M' },
  '\\lnot': { mode: 'M' },
  '\\lnsim': { mode: 'M' },
  '\\log': { mode: 'M' },
  '\\long': { mode: 'M' },
  '\\Longleftarrow': { mode: 'M' },
  '\\longleftarrow': { mode: 'M' },
  '\\Longleftrightarrow': { mode: 'M' },
  '\\longleftrightarrow': { mode: 'M' },
  '\\longmapsto': { mode: 'M' },
  '\\Longrightarrow': { mode: 'M' },
  '\\longrightarrow': { mode: 'M' },
  '\\looparrowleft': { mode: 'M' },
  '\\looparrowright': { mode: 'M' },
  '\\lor': { mode: 'M' },
  '\\lozenge': { mode: 'M' },
  '\\lparen': { mode: 'M' },
  '\\Lrarr': { mode: 'M' },
  '\\lrArr': { mode: 'M' },
  '\\lrarr': { mode: 'M' },
  '\\lrcorner': { mode: 'M' },
  '\\lq': { mode: 'M' },
  '\\Lsh': { mode: 'M' },
  '\\lt': { mode: 'M' },
  '\\ltimes': { mode: 'M' },
  '\\lVert': { mode: 'M' },
  '\\lvert': { mode: 'M' },
  '\\lvertneqq': { mode: 'M' },
  '\\maltese': { mode: 'M' },
  '\\mapsto': { mode: 'M' },
  '\\mathbb': { mode: 'M' },
  '\\mathbf': { mode: 'M' },
  '\\mathbin': { mode: 'M' },
  '\\mathcal': { mode: 'M' },
  '\\mathchoice': { mode: 'M' },
  '\\mathclap': { mode: 'M' },
  '\\mathclose': { mode: 'M' },
  '\\mathellipsis': { mode: 'M' },
  '\\mathfrak': { mode: 'M' },
  '\\mathinner': { mode: 'M' },
  '\\mathit': { mode: 'M' },
  '\\mathllap': { mode: 'M' },
  '\\mathnormal': { mode: 'M' },
  '\\mathop': { mode: 'M' },
  '\\mathopen': { mode: 'M' },
  '\\mathord': { mode: 'M' },
  '\\mathpunct': { mode: 'M' },
  '\\mathrel': { mode: 'M' },
  '\\mathrlap': { mode: 'M' },
  '\\mathring': { mode: 'M' },
  '\\mathrm': { mode: 'M' },
  '\\mathscr': { mode: 'M' },
  '\\mathsf': { mode: 'M' },
  '\\mathsterling': { mode: 'M' },
  '\\mathtt': { mode: 'M' },
  '\\max': { mode: 'M' },
  '\\measuredangle': { mode: 'M' },
  '\\medspace': { mode: 'M' },
  '\\mho': { mode: 'M' },
  '\\mid': { mode: 'M' },
  '\\middle': { mode: 'M' },
  '\\min': { mode: 'M' },
  '\\minuso': { mode: 'M' },
  '\\mkern': { mode: 'M' },
  '\\mod': { mode: 'M' },
  '\\models': { mode: 'M' },
  '\\mp': { mode: 'M' },
  '\\mskip': { mode: 'M' },
  '\\Mu': { mode: 'M' },
  '\\mu': { mode: 'M' },
  '\\multimap': { mode: 'M' },
  '\\N': { mode: 'M' },
  '\\nabla': { mode: 'M' },
  '\\natnums': { mode: 'M' },
  '\\natural': { mode: 'M' },
  '\\negmedspace': { mode: 'M' },
  '\\ncong': { mode: 'M' },
  '\\ne': { mode: 'M' },
  '\\nearrow': { mode: 'M' },
  '\\neg': { mode: 'M' },
  '\\negthickspace': { mode: 'M' },
  '\\negthinspace': { mode: 'M' },
  '\\neq': { mode: 'M' },
  '\\newline': { mode: 'M' },
  '\\nexists': { mode: 'M' },
  '\\ngeq': { mode: 'M' },
  '\\ngeqq': { mode: 'M' },
  '\\ngeqslant': { mode: 'M' },
  '\\ngtr': { mode: 'M' },
  '\\ni': { mode: 'M' },
  '\\nleftarrow': { mode: 'M' },
  '\\nLeftarrow': { mode: 'M' },
  '\\nLeftrightarrow': { mode: 'M' },
  '\\nleftrightarrow': { mode: 'M' },
  '\\nleq': { mode: 'M' },
  '\\nleqq': { mode: 'M' },
  '\\nleqslant': { mode: 'M' },
  '\\nless': { mode: 'M' },
  '\\nmid': { mode: 'M' },
  '\\nobreak': { mode: 'M' },
  '\\nobreakspace': { mode: 'M' },
  '\\noexpand': { mode: 'M' },
  '\\nolimits': { mode: 'M' },
  '\\normalsize': { mode: 'M' },
  '\\not': { mode: 'M' },
  '\\notin': { mode: 'M' },
  '\\notni': { mode: 'M' },
  '\\nparallel': { mode: 'M' },
  '\\nprec': { mode: 'M' },
  '\\npreceq': { mode: 'M' },
  '\\nRightarrow': { mode: 'M' },
  '\\nrightarrow': { mode: 'M' },
  '\\nshortmid': { mode: 'M' },
  '\\nshortparallel': { mode: 'M' },
  '\\nsim': { mode: 'M' },
  '\\nsubseteq': { mode: 'M' },
  '\\nsubseteqq': { mode: 'M' },
  '\\nsucc': { mode: 'M' },
  '\\nsucceq': { mode: 'M' },
  '\\nsupseteq': { mode: 'M' },
  '\\nsupseteqq': { mode: 'M' },
  '\\ntriangleleft': { mode: 'M' },
  '\\ntrianglelefteq': { mode: 'M' },
  '\\ntriangleright': { mode: 'M' },
  '\\ntrianglerighteq': { mode: 'M' },
  '\\Nu': { mode: 'M' },
  '\\nu': { mode: 'M' },
  '\\nVDash': { mode: 'M' },
  '\\nVdash': { mode: 'M' },
  '\\nvDash': { mode: 'M' },
  '\\nvdash': { mode: 'M' },
  '\\nwarrow': { mode: 'M' },
  '\\odot': { mode: 'M' },
  '\\oiiint': { mode: 'M' },
  '\\oiint': { mode: 'M' },
  '\\oint': { mode: 'M' },
  '\\omega': { mode: 'M' },
  '\\Omega': { mode: 'M' },
  '\\Omicron': { mode: 'M' },
  '\\omicron': { mode: 'M' },
  '\\ominus': { mode: 'M' },
  '\\operatorname': { mode: 'M' },
  '\\oplus': { mode: 'M' },
  '\\oslash': { mode: 'M' },
  '\\otimes': { mode: 'M' },
  '\\over': { mode: 'M' },
  '\\overbrace': { mode: 'M' },
  '\\overgroup': { mode: 'M' },
  '\\overleftarrow': { mode: 'M' },
  '\\overleftharpoon': { mode: 'M' },
  '\\overleftrightarrow': { mode: 'M' },
  '\\overline': { mode: 'M' },
  '\\overlinesegment': { mode: 'M' },
  '\\Overrightarrow': { mode: 'M' },
  '\\overrightarrow': { mode: 'M' },
  '\\overrightharpoon': { mode: 'M' },
  '\\overset': { mode: 'M' },
  '\\owns': { mode: 'M' },
  '\\P': { mode: 'M' },
  '\\parallel': { mode: 'M' },
  '\\partial': { mode: 'M' },
  '\\perp': { mode: 'M' },
  '\\phantom': { mode: 'M' },
  '\\Phi': { mode: 'M' },
  '\\phi': { mode: 'M' },
  '\\Pi': { mode: 'M' },
  '\\pi': { mode: 'M' },
  '\\pitchfork': { mode: 'M' },
  '\\plim': { mode: 'M' },
  '\\plusmn': { mode: 'M' },
  '\\pm': { mode: 'M' },
  '\\pmb': { mode: 'M' },
  '\\pmod': { mode: 'M' },
  '\\pod': { mode: 'M' },
  '\\pounds': { mode: 'M' },
  '\\Pr': { mode: 'M' },
  '\\prec': { mode: 'M' },
  '\\precapprox': { mode: 'M' },
  '\\preccurlyeq': { mode: 'M' },
  '\\preceq': { mode: 'M' },
  '\\precnapprox': { mode: 'M' },
  '\\precneqq': { mode: 'M' },
  '\\precnsim': { mode: 'M' },
  '\\precsim': { mode: 'M' },
  '\\prime': { mode: 'M' },
  '\\prod': { mode: 'M' },
  '\\propto': { mode: 'M' },
  '\\providecommand': { mode: 'M' },
  '\\psi': { mode: 'M' },
  '\\Psi': { mode: 'M' },
  '\\R': { mode: 'M' },
  '\\raisebox': { mode: 'M' },
  '\\rang': { mode: 'M' },
  '\\rangle': { mode: 'M' },
  '\\Rarr': { mode: 'M' },
  '\\rArr': { mode: 'M' },
  '\\rarr': { mode: 'M' },
  '\\rBrace': { mode: 'M' },
  '\\rbrace': { mode: 'M' },
  '\\rbrack': { mode: 'M' },
  '\\rceil': { mode: 'M' },
  '\\Re': { mode: 'M' },
  '\\real': { mode: 'M' },
  '\\Reals': { mode: 'M' },
  '\\reals': { mode: 'M' },
  '\\relax': { mode: 'M' },
  '\\hail': { mode: 'M' },
  '\\restriction': { mode: 'M' },
  '\\rfloor': { mode: 'M' },
  '\\rgroup': { mode: 'M' },
  '\\rhd': { mode: 'M' },
  '\\Rho': { mode: 'M' },
  '\\rho': { mode: 'M' },
  '\\right': { mode: 'M' },
  '\\Rightarrow': { mode: 'M' },
  '\\rightarrow': { mode: 'M' },
  '\\rightarrowtail': { mode: 'M' },
  '\\rightharpoondown': { mode: 'M' },
  '\\rightharpoonup': { mode: 'M' },
  '\\rightleftarrows': { mode: 'M' },
  '\\rightleftharpoons': { mode: 'M' },
  '\\rightrightarrows': { mode: 'M' },
  '\\rightsquigarrow': { mode: 'M' },
  '\\rightthreetimes': { mode: 'M' },
  '\\risingdotseq': { mode: 'M' },
  '\\rlap': { mode: 'M' },
  '\\rmoustache': { mode: 'M' },
  '\\rparen': { mode: 'M' },
  '\\rq': { mode: 'M' },
  '\\rrbracket': { mode: 'M' },
  '\\Rrightarrow': { mode: 'M' },
  '\\Rsh': { mode: 'M' },
  '\\rtimes': { mode: 'M' },
  '\\rule': { mode: 'M' },
  '\\rVert': { mode: 'M' },
  '\\rvert': { mode: 'M' },
  '\\scriptscriptstyle': { mode: 'M' },
  '\\scriptsize': { mode: 'M' },
  '\\scriptstyle': { mode: 'M' },
  '\\sdot': { mode: 'M' },
  '\\searrow': { mode: 'M' },
  '\\sec': { mode: 'M' },
  '\\sect': { mode: 'M' },
  '\\setminus': { mode: 'M' },
  '\\sf': { mode: 'M' },
  '\\sharp': { mode: 'M' },
  '\\shortmid': { mode: 'M' },
  '\\shortparallel': { mode: 'M' },
  '\\Sigma': { mode: 'M' },
  '\\sigma': { mode: 'M' },
  '\\sim': { mode: 'M' },
  '\\simeq': { mode: 'M' },
  '\\sin': { mode: 'M' },
  '\\sinh': { mode: 'M' },
  '\\sixptsize': { mode: 'M' },
  '\\sh': { mode: 'M' },
  '\\small': { mode: 'M' },
  '\\smallfrown': { mode: 'M' },
  '\\smallint': { mode: 'M' },
  '\\smallsetminus': { mode: 'M' },
  '\\smallsmile': { mode: 'M' },
  '\\smash': { mode: 'M' },
  '\\smile': { mode: 'M' },
  '\\sout': { mode: 'M' },
  '\\space': { mode: 'M' },
  '\\spades': { mode: 'M' },
  '\\spadesuit': { mode: 'M' },
  '\\sphericalangle': { mode: 'M' },
  '\\sqcap': { mode: 'M' },
  '\\sqcup': { mode: 'M' },
  '\\square': { mode: 'M' },
  '\\sqrt': { mode: 'M' },
  '\\sqsubset': { mode: 'M' },
  '\\sqsubseteq': { mode: 'M' },
  '\\sqsupset': { mode: 'M' },
  '\\sqsupseteq': { mode: 'M' },
  '\\stackrel': { mode: 'M' },
  '\\star': { mode: 'M' },
  '\\sub': { mode: 'M' },
  '\\sube': { mode: 'M' },
  '\\Subset': { mode: 'M' },
  '\\subset': { mode: 'M' },
  '\\subseteq': { mode: 'M' },
  '\\subseteqq': { mode: 'M' },
  '\\subsetneq': { mode: 'M' },
  '\\subsetneqq': { mode: 'M' },
  '\\substack': { mode: 'M' },
  '\\succ': { mode: 'M' },
  '\\succapprox': { mode: 'M' },
  '\\succcurlyeq': { mode: 'M' },
  '\\succeq': { mode: 'M' },
  '\\succnapprox': { mode: 'M' },
  '\\succneqq': { mode: 'M' },
  '\\succnsim': { mode: 'M' },
  '\\succsim': { mode: 'M' },
  '\\sum': { mode: 'M' },
  '\\sup': { mode: 'M' },
  '\\supe': { mode: 'M' },
  '\\Supset': { mode: 'M' },
  '\\supset': { mode: 'M' },
  '\\supseteq': { mode: 'M' },
  '\\supseteqq': { mode: 'M' },
  '\\supsetneq': { mode: 'M' },
  '\\supsetneqq': { mode: 'M' },
  '\\surd': { mode: 'M' },
  '\\swarrow': { mode: 'M' },
  '\\tag': { mode: 'M' },
  '\\tan': { mode: 'M' },
  '\\tanh': { mode: 'M' },
  '\\Tau': { mode: 'M' },
  '\\tau': { mode: 'M' },
  '\\tbinom': { mode: 'M' },
  '\\TeX': { mode: 'M' },
  '\\text': { mode: 'M' },
  '\\tfrac': { mode: 'M' },
  '\\tg': { mode: 'M' },
  '\\th': { mode: 'M' },
  '\\therefore': { mode: 'M' },
  '\\Theta': { mode: 'M' },
  '\\theta': { mode: 'M' },
  '\\thetasym': { mode: 'M' },
  '\\thickapprox': { mode: 'M' },
  '\\thicksim': { mode: 'M' },
  '\\thickspace': { mode: 'M' },
  '\\thinspace': { mode: 'M' },
  '\\tilde': { mode: 'M' },
  '\\times': { mode: 'M' },
  '\\tiny': { mode: 'M' },
  '\\to': { mode: 'M' },
  '\\top': { mode: 'M' },
  '\\triangle': { mode: 'M' },
  '\\triangledown': { mode: 'M' },
  '\\triangleleft': { mode: 'M' },
  '\\trianglelefteq': { mode: 'M' },
  '\\triangleq': { mode: 'M' },
  '\\triangleright': { mode: 'M' },
  '\\trianglerighteq': { mode: 'M' },
  '\\tt': { mode: 'M' },
  '\\twoheadleftarrow': { mode: 'M' },
  '\\twoheadrightarrow': { mode: 'M' },
  '\\Uarr': { mode: 'M' },
  '\\uArr': { mode: 'M' },
  '\\uarr': { mode: 'M' },
  '\\ulcorner': { mode: 'M' },
  '\\underbrace': { mode: 'M' },
  '\\undergroup': { mode: 'M' },
  '\\underleftarrow': { mode: 'M' },
  '\\underleftrightarrow': { mode: 'M' },
  '\\underline': { mode: 'M' },
  '\\underlinesegment': { mode: 'M' },
  '\\underrightarrow': { mode: 'M' },
  '\\underset': { mode: 'M' },
  '\\unlhd': { mode: 'M' },
  '\\unrhd': { mode: 'M' },
  '\\Uparrow': { mode: 'M' },
  '\\uparrow': { mode: 'M' },
  '\\Updownarrow': { mode: 'M' },
  '\\updownarrow': { mode: 'M' },
  '\\upharpoonleft': { mode: 'M' },
  '\\upharpoonright': { mode: 'M' },
  '\\uplus': { mode: 'M' },
  '\\Upsilon': { mode: 'M' },
  '\\upsilon': { mode: 'M' },
  '\\upuparrows': { mode: 'M' },
  '\\urcorner': { mode: 'M' },
  '\\utilde': { mode: 'M' },
  '\\varDelta': { mode: 'M' },
  '\\varepsilon': { mode: 'M' },
  '\\varGamma': { mode: 'M' },
  '\\varkappa': { mode: 'M' },
  '\\varLambda': { mode: 'M' },
  '\\varnothing': { mode: 'M' },
  '\\varOmega': { mode: 'M' },
  '\\varPhi': { mode: 'M' },
  '\\varphi': { mode: 'M' },
  '\\varPi': { mode: 'M' },
  '\\varpi': { mode: 'M' },
  '\\varpropto': { mode: 'M' },
  '\\varPsi': { mode: 'M' },
  '\\varrho': { mode: 'M' },
  '\\varSigma': { mode: 'M' },
  '\\varsigma': { mode: 'M' },
  '\\varsubsetneq': { mode: 'M' },
  '\\varsubsetneqq': { mode: 'M' },
  '\\varsupsetneq': { mode: 'M' },
  '\\varsupsetneqq': { mode: 'M' },
  '\\varTheta': { mode: 'M' },
  '\\vartheta': { mode: 'M' },
  '\\vartriangle': { mode: 'M' },
  '\\vartriangleleft': { mode: 'M' },
  '\\vartriangleright': { mode: 'M' },
  '\\varUpsilon': { mode: 'M' },
  '\\varXi': { mode: 'M' },
  '\\vcentcolon': { mode: 'M' },
  '\\Vdash': { mode: 'M' },
  '\\vDash': { mode: 'M' },
  '\\vdash': { mode: 'M' },
  '\\vdots': { mode: 'M' },
  '\\vec': { mode: 'M' },
  '\\vee': { mode: 'M' },
  '\\veebar': { mode: 'M' },
  '\\verb': { mode: 'M' },
  '\\Vert': { mode: 'M' },
  '\\vert': { mode: 'M' },
  '\\vphantom': { mode: 'M' },
  '\\Vvdash': { mode: 'M' },
  '\\wedge': { mode: 'M' },
  '\\weierp': { mode: 'M' },
  '\\widecheck': { mode: 'M' },
  '\\widehat': { mode: 'M' },
  '\\widetilde': { mode: 'M' },
  '\\wp': { mode: 'M' },
  '\\wr': { mode: 'M' },
  '\\xcancel': { mode: 'M' },
  '\\xdef': { mode: 'M' },
  '\\Xi': { mode: 'M' },
  '\\xi': { mode: 'M' },
  '\\xhookleftarrow': { mode: 'M' },
  '\\xhookrightarrow': { mode: 'M' },
  '\\xLeftarrow': { mode: 'M' },
  '\\xleftarrow': { mode: 'M' },
  '\\xleftharpoondown': { mode: 'M' },
  '\\xleftharpoonup': { mode: 'M' },
  '\\xLeftrightarrow': { mode: 'M' },
  '\\xleftrightarrow': { mode: 'M' },
  '\\xleftrightharpoons': { mode: 'M' },
  '\\xlongequal': { mode: 'M' },
  '\\xmapsto': { mode: 'M' },
  '\\xRightarrow': { mode: 'M' },
  '\\xrightarrow': { mode: 'M' },
  '\\xrightharpoondown': { mode: 'M' },
  '\\xrightharpoonup': { mode: 'M' },
  '\\xrightleftharpoons': { mode: 'M' },
  '\\xtofrom': { mode: 'M' },
  '\\xtwoheadleftarrow': { mode: 'M' },
  '\\xtwoheadrightarrow': { mode: 'M' },
  '\\yen': { mode: 'M' },
  '\\Z': { mode: 'M' },
  '\\Zeta': { mode: 'M' },
  '\\zeta': { mode: 'M' },
};

export const environmentDictionary: { [key: string]: CompletionItem } = {
  align: { mode: 'T' },
  'align*': { mode: 'T' },
  alignat: { mode: 'T', signature: '{数量}' },
  'alignat*': { mode: 'T', signature: '{列格式}' },
  center: { mode: 'T' },
  centre: { mode: 'T' },
  corollary: { mode: 'T' },
  definition: { mode: 'T' },
  enumerate: { mode: 'T' },
  equation: { mode: 'T' },
  'equation*': { mode: 'T' },
  flushleft: { mode: 'T' },
  flushright: { mode: 'T' },
  gather: { mode: 'T' },
  'gather*': { mode: 'T' },
  lemma: { mode: 'T' },
  plaintable: { mode: 'T', signature: '{列格式}' },
  proof: { mode: 'T' },
  proposition: { mode: 'T' },
  references: { mode: 'T' },
  remark: { mode: 'T' },
  structure: { mode: 'T' },
  tabular: { mode: 'T', signature: '{列格式}' },
  thebibliography: { mode: 'T' },
  theorem: { mode: 'T' },
  tikzcd: { mode: 'T' },
  tikzpicture: { mode: 'T' },
  aligned: { mode: 'M' },
  alignedat: { mode: 'M' },
  array: { mode: 'M', signature: '{列格式}' },
  Bmatrix: { mode: 'M' },
  bmatrix: { mode: 'M' },
  cases: { mode: 'M' },
  darray: { mode: 'M' },
  dcases: { mode: 'M' },
  drcases: { mode: 'M' },
  gathered: { mode: 'M' },
  matrix: { mode: 'M' },
  pmatrix: { mode: 'M' },
  rcases: { mode: 'M' },
  smallmatrix: { mode: 'M' },
  Vmatrix: { mode: 'M' },
  vmatrix: { mode: 'M' },
};

export const snippetDictionary: { [key: string]: CompletionItem } = {
  '\\bigl( ... \\bigr)': { mode: 'M', insertText: '\\bigl( ${0} \\bigr)' },
  '\\bigl[ ... \\bigr]': { mode: 'M', insertText: '\\bigl[ ${0} \\bigr]' },
  '\\bigl\\{ ... \\bigr\\}': { mode: 'M', insertText: '\\bigl\\\\{ ${0} \\bigr\\\\}' },
  '\\bigl| ... \\bigr|': { mode: 'M', insertText: '\\bigl| ${0} \\bigr|' },
  '\\Bigl( ... \\Bigr)': { mode: 'M', insertText: '\\Bigl( ${0} \\Bigr)' },
  '\\Bigl[ ... \\Bigr]': { mode: 'M', insertText: '\\Bigl[ ${0} \\Bigr]' },
  '\\Bigl\\{ ... \\Bigr\\}': { mode: 'M', insertText: '\\Bigl\\\\{ ${0} \\Bigr\\\\}' },
  '\\Bigl| ... \\Bigr|': { mode: 'M', insertText: '\\Bigl| ${0} \\Bigr|' },
  '\\biggl( ... \\biggr)': { mode: 'M', insertText: '\\biggl( ${0} \\biggr)' },
  '\\biggl[ ... \\biggr]': { mode: 'M', insertText: '\\biggl[ ${0} \\biggr]' },
  '\\biggl\\{ ... \\biggr\\}': { mode: 'M', insertText: '\\biggl\\\\{ ${0} \\biggr\\\\}' },
  '\\biggl| ... \\biggr|': { mode: 'M', insertText: '\\biggl| ${0} \\biggr|' },
  '\\Biggl( ... \\Biggr)': { mode: 'M', insertText: '\\Biggl( ${0} \\Biggr)' },
  '\\Biggl[ ... \\Biggr]': { mode: 'M', insertText: '\\Biggl[ ${0} \\Biggr]' },
  '\\Biggl\\{ ... \\Biggr\\}': { mode: 'M', insertText: '\\Biggl\\\\{ ${0} \\Biggr\\\\}' },
  '\\Biggl| ... \\Biggr|': { mode: 'M', insertText: '\\Biggl| ${0} \\Biggr|' },
  '\\langle ... \\rangle': { mode: 'M', insertText: '\\langle ${0} \\rangle' },
  '\\left( ... \\right)': { mode: 'M', insertText: '\\left( ${0} \\right)' },
  '\\left[ ... \\right]': { mode: 'M', insertText: '\\left[ ${0} \\right]' },
  '\\left\\{ ... \\right\\}': { mode: 'M', insertText: '\\left\\\\{ ${0} \\right\\\\}' },
  '\\left| ... \\right|': { mode: 'M', insertText: '\\left| ${0} \\right|' },
};

export const strings: { [lang: string]: { [key: string]: string } } = {
  zh: {
    'unmatched-bracket': "'${1}' 没有配对。",
  },
};

export function getString(key: string, ...args: string[]): string {
  let value = (strings[options.locale] ?? strings['zh'])[key];
  if (!value) return '';

  let str = value;
  str = str.replace(/\$(_+)\{/g, '$$__$1{');
  for (let i = 0; i < args.length; i++) {
    str = str.replace('${' + (i + 1) + '}', args[i].replace(/\$(_*)\{/g, '$$__$1{'));
  }
  return str.replace(/\$__(_*)\{/g, '$$$1{');
}

export interface Import {
  uri: monaco.Uri;
  content: string;
}

export const imports: Import[] = [];
